--- #YAML:1.0
name: Alzabo-GUI-Mason
version: 0.1
author:
  - ~
abstract: A GUI for Alzabo using Mason
license: perl
requires:
  HTML::Mason: 0.896
  HTTP::BrowserDetect: 0
provides:
  Alzabo::GUI::Mason:
    file: lib/Alzabo/GUI/Mason.pm
    version: 0.1
generated_by: Module::Build version 0.23
