--- #YAML:1.0
name: Alzabo-GUI-Mason
version: 0.08
license: perl
distribution_type: module
requires:
  HTML::Mason: 0.896
  HTTP::BrowserDetect: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Alzabo::GUI::Mason:
    file: lib/Alzabo/GUI/Mason.pm
    version: 0.08
generated_by: Module::Build version 0.21
